// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.appleyk.protocol.model;

public final class SObjectModel {
  private SObjectModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.appleyk.protocol.model.Students)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    java.util.List<com.appleyk.protocol.model.SObjectModel.Students.Student> 
        getStudentsList();
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    com.appleyk.protocol.model.SObjectModel.Students.Student getStudents(int index);
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    int getStudentsCount();
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    java.util.List<? extends com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder> 
        getStudentsOrBuilderList();
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder getStudentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.appleyk.protocol.model.Students}
   */
  public  static final class Students extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.appleyk.protocol.model.Students)
      StudentsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Students.newBuilder() to construct.
    private Students(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Students() {
      students_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Students(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                students_ = new java.util.ArrayList<com.appleyk.protocol.model.SObjectModel.Students.Student>();
                mutable_bitField0_ |= 0x00000001;
              }
              students_.add(
                  input.readMessage(com.appleyk.protocol.model.SObjectModel.Students.Student.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          students_ = java.util.Collections.unmodifiableList(students_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.appleyk.protocol.model.SObjectModel.Students.class, com.appleyk.protocol.model.SObjectModel.Students.Builder.class);
    }

    public interface StudentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.appleyk.protocol.model.Students.Student)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 id = 1;</code>
       */
      long getId();

      /**
       * <code>string name = 2;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 2;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>repeated string hobbies = 3;</code>
       */
      java.util.List<java.lang.String>
          getHobbiesList();
      /**
       * <code>repeated string hobbies = 3;</code>
       */
      int getHobbiesCount();
      /**
       * <code>repeated string hobbies = 3;</code>
       */
      java.lang.String getHobbies(int index);
      /**
       * <code>repeated string hobbies = 3;</code>
       */
      com.google.protobuf.ByteString
          getHobbiesBytes(int index);

      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */
      int getGradesCount();
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */
      boolean containsGrades(
          java.lang.String key);
      /**
       * Use {@link #getGradesMap()} instead.
       */
      @java.lang.Deprecated
      java.util.Map<java.lang.String, java.lang.Double>
      getGrades();
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */
      java.util.Map<java.lang.String, java.lang.Double>
      getGradesMap();
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */

      double getGradesOrDefault(
          java.lang.String key,
          double defaultValue);
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */

      double getGradesOrThrow(
          java.lang.String key);
    }
    /**
     * Protobuf type {@code com.appleyk.protocol.model.Students.Student}
     */
    public  static final class Student extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.appleyk.protocol.model.Students.Student)
        StudentOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Student.newBuilder() to construct.
      private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Student() {
        id_ = 0L;
        name_ = "";
        hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Student(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                id_ = input.readInt64();
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                  hobbies_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000004;
                }
                hobbies_.add(s);
                break;
              }
              case 34: {
                if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                  grades_ = com.google.protobuf.MapField.newMapField(
                      GradesDefaultEntryHolder.defaultEntry);
                  mutable_bitField0_ |= 0x00000008;
                }
                com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
                grades__ = input.readMessage(
                    GradesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                grades_.getMutableMap().put(
                    grades__.getKey(), grades__.getValue());
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
            hobbies_ = hobbies_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_Student_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetGrades();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.appleyk.protocol.model.SObjectModel.Students.Student.class, com.appleyk.protocol.model.SObjectModel.Students.Student.Builder.class);
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private long id_;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }

      public static final int NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int HOBBIES_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList hobbies_;
      /**
       * <code>repeated string hobbies = 3;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHobbiesList() {
        return hobbies_;
      }
      /**
       * <code>repeated string hobbies = 3;</code>
       */
      public int getHobbiesCount() {
        return hobbies_.size();
      }
      /**
       * <code>repeated string hobbies = 3;</code>
       */
      public java.lang.String getHobbies(int index) {
        return hobbies_.get(index);
      }
      /**
       * <code>repeated string hobbies = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHobbiesBytes(int index) {
        return hobbies_.getByteString(index);
      }

      public static final int GRADES_FIELD_NUMBER = 4;
      private static final class GradesDefaultEntryHolder {
        static final com.google.protobuf.MapEntry<
            java.lang.String, java.lang.Double> defaultEntry =
                com.google.protobuf.MapEntry
                .<java.lang.String, java.lang.Double>newDefaultInstance(
                    com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_Student_GradesEntry_descriptor, 
                    com.google.protobuf.WireFormat.FieldType.STRING,
                    "",
                    com.google.protobuf.WireFormat.FieldType.DOUBLE,
                    0D);
      }
      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Double> grades_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
      internalGetGrades() {
        if (grades_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              GradesDefaultEntryHolder.defaultEntry);
        }
        return grades_;
      }

      public int getGradesCount() {
        return internalGetGrades().getMap().size();
      }
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */

      public boolean containsGrades(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetGrades().getMap().containsKey(key);
      }
      /**
       * Use {@link #getGradesMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Double> getGrades() {
        return getGradesMap();
      }
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Double> getGradesMap() {
        return internalGetGrades().getMap();
      }
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */

      public double getGradesOrDefault(
          java.lang.String key,
          double defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetGrades().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, double&gt; grades = 4;</code>
       */

      public double getGradesOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Double> map =
            internalGetGrades().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (id_ != 0L) {
          output.writeInt64(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
        }
        for (int i = 0; i < hobbies_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hobbies_.getRaw(i));
        }
        com.google.protobuf.GeneratedMessageV3
          .serializeStringMapTo(
            output,
            internalGetGrades(),
            GradesDefaultEntryHolder.defaultEntry,
            4);
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (id_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, id_);
        }
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < hobbies_.size(); i++) {
            dataSize += computeStringSizeNoTag(hobbies_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getHobbiesList().size();
        }
        for (java.util.Map.Entry<java.lang.String, java.lang.Double> entry
             : internalGetGrades().getMap().entrySet()) {
          com.google.protobuf.MapEntry<java.lang.String, java.lang.Double>
          grades__ = GradesDefaultEntryHolder.defaultEntry.newBuilderForType()
              .setKey(entry.getKey())
              .setValue(entry.getValue())
              .build();
          size += com.google.protobuf.CodedOutputStream
              .computeMessageSize(4, grades__);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.appleyk.protocol.model.SObjectModel.Students.Student)) {
          return super.equals(obj);
        }
        com.appleyk.protocol.model.SObjectModel.Students.Student other = (com.appleyk.protocol.model.SObjectModel.Students.Student) obj;

        boolean result = true;
        result = result && (getId()
            == other.getId());
        result = result && getName()
            .equals(other.getName());
        result = result && getHobbiesList()
            .equals(other.getHobbiesList());
        result = result && internalGetGrades().equals(
            other.internalGetGrades());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getId());
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        if (getHobbiesCount() > 0) {
          hash = (37 * hash) + HOBBIES_FIELD_NUMBER;
          hash = (53 * hash) + getHobbiesList().hashCode();
        }
        if (!internalGetGrades().getMap().isEmpty()) {
          hash = (37 * hash) + GRADES_FIELD_NUMBER;
          hash = (53 * hash) + internalGetGrades().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.appleyk.protocol.model.SObjectModel.Students.Student parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.appleyk.protocol.model.SObjectModel.Students.Student prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.appleyk.protocol.model.Students.Student}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.appleyk.protocol.model.Students.Student)
          com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_Student_descriptor;
        }

        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMapField(
            int number) {
          switch (number) {
            case 4:
              return internalGetGrades();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        @SuppressWarnings({"rawtypes"})
        protected com.google.protobuf.MapField internalGetMutableMapField(
            int number) {
          switch (number) {
            case 4:
              return internalGetMutableGrades();
            default:
              throw new RuntimeException(
                  "Invalid map field number: " + number);
          }
        }
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_Student_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.appleyk.protocol.model.SObjectModel.Students.Student.class, com.appleyk.protocol.model.SObjectModel.Students.Student.Builder.class);
        }

        // Construct using com.appleyk.protocol.model.SObjectModel.Students.Student.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          id_ = 0L;

          name_ = "";

          hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          internalGetMutableGrades().clear();
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_Student_descriptor;
        }

        public com.appleyk.protocol.model.SObjectModel.Students.Student getDefaultInstanceForType() {
          return com.appleyk.protocol.model.SObjectModel.Students.Student.getDefaultInstance();
        }

        public com.appleyk.protocol.model.SObjectModel.Students.Student build() {
          com.appleyk.protocol.model.SObjectModel.Students.Student result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.appleyk.protocol.model.SObjectModel.Students.Student buildPartial() {
          com.appleyk.protocol.model.SObjectModel.Students.Student result = new com.appleyk.protocol.model.SObjectModel.Students.Student(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.id_ = id_;
          result.name_ = name_;
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            hobbies_ = hobbies_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.hobbies_ = hobbies_;
          result.grades_ = internalGetGrades();
          result.grades_.makeImmutable();
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.appleyk.protocol.model.SObjectModel.Students.Student) {
            return mergeFrom((com.appleyk.protocol.model.SObjectModel.Students.Student)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.appleyk.protocol.model.SObjectModel.Students.Student other) {
          if (other == com.appleyk.protocol.model.SObjectModel.Students.Student.getDefaultInstance()) return this;
          if (other.getId() != 0L) {
            setId(other.getId());
          }
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (!other.hobbies_.isEmpty()) {
            if (hobbies_.isEmpty()) {
              hobbies_ = other.hobbies_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureHobbiesIsMutable();
              hobbies_.addAll(other.hobbies_);
            }
            onChanged();
          }
          internalGetMutableGrades().mergeFrom(
              other.internalGetGrades());
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.appleyk.protocol.model.SObjectModel.Students.Student parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.appleyk.protocol.model.SObjectModel.Students.Student) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long id_ ;
        /**
         * <code>int64 id = 1;</code>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>int64 id = 1;</code>
         */
        public Builder setId(long value) {
          
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 id = 1;</code>
         */
        public Builder clearId() {
          
          id_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 2;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 2;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureHobbiesIsMutable() {
          if (!((bitField0_ & 0x00000004) == 0x00000004)) {
            hobbies_ = new com.google.protobuf.LazyStringArrayList(hobbies_);
            bitField0_ |= 0x00000004;
           }
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public com.google.protobuf.ProtocolStringList
            getHobbiesList() {
          return hobbies_.getUnmodifiableView();
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public int getHobbiesCount() {
          return hobbies_.size();
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public java.lang.String getHobbies(int index) {
          return hobbies_.get(index);
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public com.google.protobuf.ByteString
            getHobbiesBytes(int index) {
          return hobbies_.getByteString(index);
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public Builder setHobbies(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
          hobbies_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public Builder addHobbies(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureHobbiesIsMutable();
          hobbies_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public Builder addAllHobbies(
            java.lang.Iterable<java.lang.String> values) {
          ensureHobbiesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, hobbies_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public Builder clearHobbies() {
          hobbies_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string hobbies = 3;</code>
         */
        public Builder addHobbiesBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureHobbiesIsMutable();
          hobbies_.add(value);
          onChanged();
          return this;
        }

        private com.google.protobuf.MapField<
            java.lang.String, java.lang.Double> grades_;
        private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetGrades() {
          if (grades_ == null) {
            return com.google.protobuf.MapField.emptyMapField(
                GradesDefaultEntryHolder.defaultEntry);
          }
          return grades_;
        }
        private com.google.protobuf.MapField<java.lang.String, java.lang.Double>
        internalGetMutableGrades() {
          onChanged();;
          if (grades_ == null) {
            grades_ = com.google.protobuf.MapField.newMapField(
                GradesDefaultEntryHolder.defaultEntry);
          }
          if (!grades_.isMutable()) {
            grades_ = grades_.copy();
          }
          return grades_;
        }

        public int getGradesCount() {
          return internalGetGrades().getMap().size();
        }
        /**
         * <code>map&lt;string, double&gt; grades = 4;</code>
         */

        public boolean containsGrades(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          return internalGetGrades().getMap().containsKey(key);
        }
        /**
         * Use {@link #getGradesMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.Double> getGrades() {
          return getGradesMap();
        }
        /**
         * <code>map&lt;string, double&gt; grades = 4;</code>
         */

        public java.util.Map<java.lang.String, java.lang.Double> getGradesMap() {
          return internalGetGrades().getMap();
        }
        /**
         * <code>map&lt;string, double&gt; grades = 4;</code>
         */

        public double getGradesOrDefault(
            java.lang.String key,
            double defaultValue) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, java.lang.Double> map =
              internalGetGrades().getMap();
          return map.containsKey(key) ? map.get(key) : defaultValue;
        }
        /**
         * <code>map&lt;string, double&gt; grades = 4;</code>
         */

        public double getGradesOrThrow(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          java.util.Map<java.lang.String, java.lang.Double> map =
              internalGetGrades().getMap();
          if (!map.containsKey(key)) {
            throw new java.lang.IllegalArgumentException();
          }
          return map.get(key);
        }

        public Builder clearGrades() {
          internalGetMutableGrades().getMutableMap()
              .clear();
          return this;
        }
        /**
         * <code>map&lt;string, double&gt; grades = 4;</code>
         */

        public Builder removeGrades(
            java.lang.String key) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          internalGetMutableGrades().getMutableMap()
              .remove(key);
          return this;
        }
        /**
         * Use alternate mutation accessors instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, java.lang.Double>
        getMutableGrades() {
          return internalGetMutableGrades().getMutableMap();
        }
        /**
         * <code>map&lt;string, double&gt; grades = 4;</code>
         */
        public Builder putGrades(
            java.lang.String key,
            double value) {
          if (key == null) { throw new java.lang.NullPointerException(); }
          
          internalGetMutableGrades().getMutableMap()
              .put(key, value);
          return this;
        }
        /**
         * <code>map&lt;string, double&gt; grades = 4;</code>
         */

        public Builder putAllGrades(
            java.util.Map<java.lang.String, java.lang.Double> values) {
          internalGetMutableGrades().getMutableMap()
              .putAll(values);
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.appleyk.protocol.model.Students.Student)
      }

      // @@protoc_insertion_point(class_scope:com.appleyk.protocol.model.Students.Student)
      private static final com.appleyk.protocol.model.SObjectModel.Students.Student DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.appleyk.protocol.model.SObjectModel.Students.Student();
      }

      public static com.appleyk.protocol.model.SObjectModel.Students.Student getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Student>
          PARSER = new com.google.protobuf.AbstractParser<Student>() {
        public Student parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Student(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Student> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Student> getParserForType() {
        return PARSER;
      }

      public com.appleyk.protocol.model.SObjectModel.Students.Student getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int STUDENTS_FIELD_NUMBER = 1;
    private java.util.List<com.appleyk.protocol.model.SObjectModel.Students.Student> students_;
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    public java.util.List<com.appleyk.protocol.model.SObjectModel.Students.Student> getStudentsList() {
      return students_;
    }
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    public java.util.List<? extends com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder> 
        getStudentsOrBuilderList() {
      return students_;
    }
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    public int getStudentsCount() {
      return students_.size();
    }
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    public com.appleyk.protocol.model.SObjectModel.Students.Student getStudents(int index) {
      return students_.get(index);
    }
    /**
     * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
     */
    public com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder getStudentsOrBuilder(
        int index) {
      return students_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < students_.size(); i++) {
        output.writeMessage(1, students_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < students_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, students_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.appleyk.protocol.model.SObjectModel.Students)) {
        return super.equals(obj);
      }
      com.appleyk.protocol.model.SObjectModel.Students other = (com.appleyk.protocol.model.SObjectModel.Students) obj;

      boolean result = true;
      result = result && getStudentsList()
          .equals(other.getStudentsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStudentsCount() > 0) {
        hash = (37 * hash) + STUDENTS_FIELD_NUMBER;
        hash = (53 * hash) + getStudentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.appleyk.protocol.model.SObjectModel.Students parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.appleyk.protocol.model.SObjectModel.Students prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.appleyk.protocol.model.Students}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.appleyk.protocol.model.Students)
        com.appleyk.protocol.model.SObjectModel.StudentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.appleyk.protocol.model.SObjectModel.Students.class, com.appleyk.protocol.model.SObjectModel.Students.Builder.class);
      }

      // Construct using com.appleyk.protocol.model.SObjectModel.Students.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStudentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.appleyk.protocol.model.SObjectModel.internal_static_com_appleyk_protocol_model_Students_descriptor;
      }

      public com.appleyk.protocol.model.SObjectModel.Students getDefaultInstanceForType() {
        return com.appleyk.protocol.model.SObjectModel.Students.getDefaultInstance();
      }

      public com.appleyk.protocol.model.SObjectModel.Students build() {
        com.appleyk.protocol.model.SObjectModel.Students result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.appleyk.protocol.model.SObjectModel.Students buildPartial() {
        com.appleyk.protocol.model.SObjectModel.Students result = new com.appleyk.protocol.model.SObjectModel.Students(this);
        int from_bitField0_ = bitField0_;
        if (studentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            students_ = java.util.Collections.unmodifiableList(students_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.students_ = students_;
        } else {
          result.students_ = studentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.appleyk.protocol.model.SObjectModel.Students) {
          return mergeFrom((com.appleyk.protocol.model.SObjectModel.Students)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.appleyk.protocol.model.SObjectModel.Students other) {
        if (other == com.appleyk.protocol.model.SObjectModel.Students.getDefaultInstance()) return this;
        if (studentsBuilder_ == null) {
          if (!other.students_.isEmpty()) {
            if (students_.isEmpty()) {
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStudentsIsMutable();
              students_.addAll(other.students_);
            }
            onChanged();
          }
        } else {
          if (!other.students_.isEmpty()) {
            if (studentsBuilder_.isEmpty()) {
              studentsBuilder_.dispose();
              studentsBuilder_ = null;
              students_ = other.students_;
              bitField0_ = (bitField0_ & ~0x00000001);
              studentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStudentsFieldBuilder() : null;
            } else {
              studentsBuilder_.addAllMessages(other.students_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.appleyk.protocol.model.SObjectModel.Students parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.appleyk.protocol.model.SObjectModel.Students) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.appleyk.protocol.model.SObjectModel.Students.Student> students_ =
        java.util.Collections.emptyList();
      private void ensureStudentsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          students_ = new java.util.ArrayList<com.appleyk.protocol.model.SObjectModel.Students.Student>(students_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.appleyk.protocol.model.SObjectModel.Students.Student, com.appleyk.protocol.model.SObjectModel.Students.Student.Builder, com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder> studentsBuilder_;

      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public java.util.List<com.appleyk.protocol.model.SObjectModel.Students.Student> getStudentsList() {
        if (studentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(students_);
        } else {
          return studentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public int getStudentsCount() {
        if (studentsBuilder_ == null) {
          return students_.size();
        } else {
          return studentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public com.appleyk.protocol.model.SObjectModel.Students.Student getStudents(int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);
        } else {
          return studentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder setStudents(
          int index, com.appleyk.protocol.model.SObjectModel.Students.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.set(index, value);
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder setStudents(
          int index, com.appleyk.protocol.model.SObjectModel.Students.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.set(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder addStudents(com.appleyk.protocol.model.SObjectModel.Students.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder addStudents(
          int index, com.appleyk.protocol.model.SObjectModel.Students.Student value) {
        if (studentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStudentsIsMutable();
          students_.add(index, value);
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder addStudents(
          com.appleyk.protocol.model.SObjectModel.Students.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder addStudents(
          int index, com.appleyk.protocol.model.SObjectModel.Students.Student.Builder builderForValue) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.add(index, builderForValue.build());
          onChanged();
        } else {
          studentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder addAllStudents(
          java.lang.Iterable<? extends com.appleyk.protocol.model.SObjectModel.Students.Student> values) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, students_);
          onChanged();
        } else {
          studentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder clearStudents() {
        if (studentsBuilder_ == null) {
          students_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          studentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public Builder removeStudents(int index) {
        if (studentsBuilder_ == null) {
          ensureStudentsIsMutable();
          students_.remove(index);
          onChanged();
        } else {
          studentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public com.appleyk.protocol.model.SObjectModel.Students.Student.Builder getStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder getStudentsOrBuilder(
          int index) {
        if (studentsBuilder_ == null) {
          return students_.get(index);  } else {
          return studentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public java.util.List<? extends com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder> 
           getStudentsOrBuilderList() {
        if (studentsBuilder_ != null) {
          return studentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(students_);
        }
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public com.appleyk.protocol.model.SObjectModel.Students.Student.Builder addStudentsBuilder() {
        return getStudentsFieldBuilder().addBuilder(
            com.appleyk.protocol.model.SObjectModel.Students.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public com.appleyk.protocol.model.SObjectModel.Students.Student.Builder addStudentsBuilder(
          int index) {
        return getStudentsFieldBuilder().addBuilder(
            index, com.appleyk.protocol.model.SObjectModel.Students.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .com.appleyk.protocol.model.Students.Student students = 1;</code>
       */
      public java.util.List<com.appleyk.protocol.model.SObjectModel.Students.Student.Builder> 
           getStudentsBuilderList() {
        return getStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.appleyk.protocol.model.SObjectModel.Students.Student, com.appleyk.protocol.model.SObjectModel.Students.Student.Builder, com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder> 
          getStudentsFieldBuilder() {
        if (studentsBuilder_ == null) {
          studentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.appleyk.protocol.model.SObjectModel.Students.Student, com.appleyk.protocol.model.SObjectModel.Students.Student.Builder, com.appleyk.protocol.model.SObjectModel.Students.StudentOrBuilder>(
                  students_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          students_ = null;
        }
        return studentsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.appleyk.protocol.model.Students)
    }

    // @@protoc_insertion_point(class_scope:com.appleyk.protocol.model.Students)
    private static final com.appleyk.protocol.model.SObjectModel.Students DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.appleyk.protocol.model.SObjectModel.Students();
    }

    public static com.appleyk.protocol.model.SObjectModel.Students getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Students>
        PARSER = new com.google.protobuf.AbstractParser<Students>() {
      public Students parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Students(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Students> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Students> getParserForType() {
      return PARSER;
    }

    public com.appleyk.protocol.model.SObjectModel.Students getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appleyk_protocol_model_Students_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appleyk_protocol_model_Students_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appleyk_protocol_model_Students_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appleyk_protocol_model_Students_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_appleyk_protocol_model_Students_Student_GradesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_appleyk_protocol_model_Students_Student_GradesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rStudent.proto\022\032com.appleyk.protocol.mo" +
      "del\"\372\001\n\010Students\022>\n\010students\030\001 \003(\0132,.com" +
      ".appleyk.protocol.model.Students.Student" +
      "\032\255\001\n\007Student\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017" +
      "\n\007hobbies\030\003 \003(\t\022H\n\006grades\030\004 \003(\01328.com.ap" +
      "pleyk.protocol.model.Students.Student.Gr" +
      "adesEntry\032-\n\013GradesEntry\022\013\n\003key\030\001 \001(\t\022\r\n" +
      "\005value\030\002 \001(\001:\0028\001B\016B\014SObjectModelb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_appleyk_protocol_model_Students_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_appleyk_protocol_model_Students_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appleyk_protocol_model_Students_descriptor,
        new java.lang.String[] { "Students", });
    internal_static_com_appleyk_protocol_model_Students_Student_descriptor =
      internal_static_com_appleyk_protocol_model_Students_descriptor.getNestedTypes().get(0);
    internal_static_com_appleyk_protocol_model_Students_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appleyk_protocol_model_Students_Student_descriptor,
        new java.lang.String[] { "Id", "Name", "Hobbies", "Grades", });
    internal_static_com_appleyk_protocol_model_Students_Student_GradesEntry_descriptor =
      internal_static_com_appleyk_protocol_model_Students_Student_descriptor.getNestedTypes().get(0);
    internal_static_com_appleyk_protocol_model_Students_Student_GradesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_appleyk_protocol_model_Students_Student_GradesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
